batch_size: 64
data: SEP
device: cuda
drop_out_act: 0.1
drop_out_d: 0.1
emb_size_act: 4
epochs: 3000
epochs_pre_train: 200
gd_ratio: 2
lr_dis: 0.0001
lr_gen_act: 0.0001
n_head_act: 4
n_head_d: 2
n_hid_act: 64
n_hid_d: 8
n_layer_act: 3
n_layer_d: 2
seed: 88
seq_len: 59
seq_num: 900
test_size: 0
train_size: 900
valid_size: 0
vocab_num_act: 16
w_a: 100
w_g: 1
