batch_size: 512
data: SEP
device: cuda
drop_out: 0.1
emb_size: 8
epochs: 1000
lr: 0.0001
n_head: 4
n_hid: 64
n_layer: 3
ndsize: 64
seed: 77
seq_len: 59
seq_num: 900
test_neg_num: 450
test_pos_num: 90
train_neg_num: 3600
train_pos_num: 720
val_neg_num: 450
val_pos_num: 90
vocab_num: 16